export const MCFU_REGISTRATION_FEE_FULL = 250;
export const MCFU_MEMBERSHIP_FEE_FULL = 250;
export const MCFU_REGISTRATION_FEE_REDUCED = 100;
export const MCFU_MEMBERSHIP_FEE_REDUCED = 100;

export const MIN_REGISTRATION_AGE = 14;
